format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: FREERTOS_DAEMON_TASK_STARTUP_HOOK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: 'true'}
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: FREERTOS_EXPECTED_IDLE_TIME_BEFORE_SLEEP}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: FREERTOS_INCLUDE_XTASKRESUMEFROMISR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Combo
    attributes: {id: FREERTOS_TICKLESS_IDLE_CHOICE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Tick_Interrupt}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_QUEUE_LENGTH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '10'}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_TASK_PRIORITY}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '3'}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_TASK_STACK_DEPTH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '256'}
  - type: Boolean
    attributes: {id: FREERTOS_USE_QUEUE_SETS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: FREERTOS_USE_TIMERS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '460', y: '20', id: FreeRTOS}
